### ISSUE TITLE
Server Settings are not saved

### ISSUE THREAD

**Issue by am7c7** [KonsecGmbH/intellij-onedev-plugin#10]
After restart settings of server are lost 
- token setting is filled into password field
- mTLS and P12 are empty.

**Comment by alex-sc** [comment]
FYI: Debug info. OneDev repository settings will be saved under the `OneDev` tag in `.idea/workspace.xml`. I will debug the code a bit a push and fix today. You can inspect the file for debug purposes. The tag is not there yet, this is the root cause of these issues


```lang=xml
    <servers>
      <GitHub url="https://github.com" />
      <OneDev url="http://127.0.0.1:6610">
        <option name="mutualTlsCertificatePassword" value="" />
        <option name="mutualTlsCertificatePath" value="" />
        <option name="searchQuery" value="" />
        <option name="useAccessToken" value="true" />
      </OneDev>
    </servers>
```
