### ISSUE TITLE
Automate release to marketplace

### ISSUE THREAD

**Issue by am7c7** [KonsecGmbH/intellij-onedev-plugin#14]
With github actions.

**Comment by am7c7** [comment]
I've added the secret in the org.

**Comment by am7c7** [comment]
Can you make a release?

**Comment by alex-sc** [comment]
Let me try in 5 min

**Comment by alex-sc** [comment]
@am7c7 Can you see it? The action has completed w/o errors

**Comment by am7c7** [comment]
Yes, great.
