### ISSUE TITLE
SSL with self signed certificate doesn't work

### ISSUE THREAD

**Issue by jnehlmeier** [KonsecGmbH/intellij-onedev-plugin#15]
I have OneDev installed behind NGINX proxy which provides SSL using a server certificate that is signed with a self signed CA certificate.

If I use Postman or Hoppscotch, configure it to not verify SSL certificates and then call the URL manually, e.g. 
```
https://onedev.example.com/~api/projects?offset=0&count=1

Authorization Basic base64(user:<accesstoken>)
```
then I receive a result successfully. 

In IntelliJ in `Settings -> Tools -> Server Certificates` I have checked `Accept non-trusted certificates automatically` and to be double sure added the self signed CA certificate and the server certificate to the list of trusted certificates.

However the plugin is not able to connect to OneDev. It always receives HTTP 400 Bad request. If I temporarly publish OneDev directly without SSL and use the HTTP address instead the plugin works as expected.

Given that Postman/Hoppscotch using the SSL URL works I don't think it is an NGINX configuration issue but a plugin SSL issue with self signed certificates.

**Comment by jnehlmeier** [comment]
Maybe the HTTP client used in the plugin connects to the SSL endpoint without SSL? I am not using mTLS.

**Comment by alex-sc** [comment]
@jnehlmeier I will take a look in the evening. Thanks for reporting!

**Comment by am7c7** [comment]
Weird, we use the platform http client if mTLS is not selected. Can you add the self-signed cert to Settings -> Tools -> Server Certificates ?

**Comment by jnehlmeier** [comment]
> Weird, we use the platform http client if mTLS is not selected. Can you add the self-signed cert to Settings -> Tools -> Server Certificates ?

I have already done that as written above.

**Comment by alex-sc** [comment]
@jnehlmeier Does the self-signed certificate hostname (CN) match the actual DNS hostname? I'm able to reproduce such case

I suspect  the "Accept non-trusted certificates automatically" only makes the self-signed certificate trusted, but it doesn't disable the hostname verification

**Comment by jnehlmeier** [comment]
@alex-sc The common name does not match the DNS hostname because the server certificate is a SAN certificate with multiple DNS and wildcard DNS names. That single certificate is used for all kinds of development hostnames/services, e.g.

- example.com
- *.example.com (which covers onedev.example.com)
- *.build.example.com
- *.nightly.example.com

**Comment by jnehlmeier** [comment]
The cert is created using easyrsa tool using `easyrsa --subject-alt-name="DNS:example.com,DNS:*.example.com" build-server-full example.com-20241128`. 

The self signed CA is valid for 10 years and the server cert is valid for 1 year + 30 days. Both use elliptic curve secp384r1 with sha256. So nothing special.

**Comment by alex-sc** [comment]
@jnehlmeier 

Are you sure it's not something dead simple like http:// vs https://

Let's try to debug if Nginx or DevOne is returning those 400s

```
log_format upstream_status '$remote_addr $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$upstream_status"';

server {
...
    access_log /dev/stdout upstream_status;
...
```

Requests served by Nginx will have no value in the last log column, while ones proxies and served by OveDev will have a value like "400" (actual response code)

<img width="1300" alt="Screenshot 2024-11-28 at 19 25 56" src="https://github.com/user-attachments/assets/85d6561e-1f11-4250-835b-7b2884306079">

**Comment by jnehlmeier** [comment]
@alex-sc looks like NGINX returns 400. Last field in the log is upstream status:

```
Request via IntelliJ plugin (no upstream status):

10.0.0.2 - user [28/Nov/2024:17:35:18 +0000] "GET /~api/projects?offset=0&count=1 HTTP/1.1" 400 157 "-" "Apache-HttpClient/4.5.14 (Java/21.0.5)" "-" "-"



Request via Postman/Hoppscotch (status 200)

10.0.0.2 - user [28/Nov/2024:17:36:30 +0000] "GET /~api/projects?offset=0&count=1 HTTP/1.1" 200 574 "-" "-" "-" "200"
```

**Comment by alex-sc** [comment]
@jnehlmeier Any special TLS configuration maybe?

**Comment by alex-sc** [comment]
Enough guesses I think. I will create a debug version of the plugin with some better logging

**Comment by jnehlmeier** [comment]
No. In NGINX we only provide `ssl_certificate` and `ssl_certificate_key` and then turn on ssl on the various `server {}` blocks we have.

```
server {
    listen 443 ssl;
    server_name onedev.example.com;

    location /wicket/websocket {
        include /etc/nginx/proxy.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $proxy_connection;
        set $upstream onedev;
        proxy_pass http://$upstream:6610$request_uri;
    }

    location /~server {
        include /etc/nginx/proxy.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $proxy_connection;
        set $upstream onedev;
        proxy_pass http://$upstream:6610$request_uri;
    }

    location / {
        include /etc/nginx/proxy.conf;
        set $upstream onedev;
        proxy_pass http://$upstream:6610;
    }
}
```

We use `set $upstream onedev;` because NGINX + OneDev run in Docker Swarm and we want NGINX to lookup DNS everytime in case the container IP has changed.

The included `proxy.conf` looks like
```
# Common Proxy Settings
client_max_body_size 0;
proxy_http_version 1.1;
proxy_buffering off;
proxy_redirect off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Scheme $scheme;
proxy_set_header X-Forwarded-Port $server_port;
# 1 hour timeout
proxy_connect_timeout 3600s;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
send_timeout 3600s;

# Non-Standard X-Forwarded-Proto
proxy_set_header X-Forwarded-Ssl on;
```

**Comment by jnehlmeier** [comment]
@alex-sc Debugging revealed that the request from the IntelliJ plugin does send the `Authorization` header twice. Nginx then complains about duplicate HTTP headers and returns status 400.

NGINX log prints the headers in the following order:
```
Authorization: Basic xxxxxxxxx
Host: ...
Connection: ...
User-Agent: Apache....
Accept-Encoding: ...
Authorization: Basic xxxxxxxxx (this line is not shown, instead NGINX logs "client sent duplicate header line Authorization....")
```

Postman/Hoppscotch only send a single `Authorization` header and thus it works in these tools. My gut feeling says that the `Authorization` header before the `Host` header looks weird. Usually `Host` is the first header in a request.

**Comment by alex-sc** [comment]
@jnehlmeier 

Thanks, I've fixed the issue. I saw it, but didn't think it could be the cause. Let's test on a new build

You can either download a plugin build here https://github.com/KonsecGmbH/intellij-onedev-plugin/actions/runs/12083862823/artifacts/2253513126 or wait for @am7c7 to push it to the marketplace

**Comment by jnehlmeier** [comment]
Great. I will wait for the marketplace update then.

**Comment by am7c7** [comment]
Release is out.

**Comment by jnehlmeier** [comment]
It works now 👍

**Comment by alex-sc** [comment]
@jnehlmeier That was a simple but also a really weird issue to me. Thanks for your help and patience in debugging it!

I will add a test case for Nginx TLS termination
