### ISSUE TITLE
Wrong issue is closed

### ISSUE THREAD

**Issue by am7c7** [KonsecGmbH/intellij-onedev-plugin#16]
I close a task in idea, but a different task in a different project is closed.

**Comment by alex-sc** [comment]
@am7c7 Are you using v0.0.7?

**Comment by alex-sc** [comment]
I believe I've fixed this bug in 0.0.7. Make sure to delete any locally cached tasks

**Comment by am7c7** [comment]
Thanks, I've rebuilt the plugin locally with the current main and it worked this time.
